const API="/api/v1";let state={markets:[],marketplaces:[],opportunities:[],sources:[],runs:[],filter:"all"};let loadInFlight=null;
const $=s=>document.querySelector(s);const money=(v,c)=>v==null?"—":new Intl.NumberFormat("ru-RU",{style:"currency",currency:c,maximumFractionDigits:0}).format(v);
async function request(path,options={}){const response=await fetch(API+path,{cache:"no-store",headers:{"Content-Type":"application/json"},...options});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`Ошибка ${response.status}`)}return response.status===204?null:response.json()}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2600)}
function statusLabel(status){return({new:"Новая",evaluating:"На оценке",accepted:"Принята",rejected:"Отклонена",expired:"Истекла",acquired:"Куплена"})[status]||status}
function priorityLabel(label){return({priority:"Приоритет",review:"Требует анализа",low:"Низкий приоритет",unscored:"Без оценки"})[label]||label}
function acceptedProfit(){const totals={};state.opportunities.filter(x=>["accepted","acquired"].includes(x.status)).forEach(x=>{if(x.expected_profit!=null)totals[x.currency]=(totals[x.currency]||0)+Number(x.expected_profit)});const entries=Object.entries(totals);return entries.length?entries.map(([currency,value])=>money(value,currency)).join(" + "):"0"}
function render(){const list=state.filter==="all"?state.opportunities:state.opportunities.filter(x=>x.status===state.filter);$("#metric-total").textContent=state.opportunities.length;$("#metric-review").textContent=state.opportunities.filter(x=>["new","evaluating"].includes(x.status)).length;$("#metric-accepted").textContent=state.opportunities.filter(x=>["accepted","acquired"].includes(x.status)).length;$("#metric-profit").textContent=acceptedProfit();$("#setup").classList.toggle("hidden",state.markets.length>0&&state.marketplaces.length>0);const root=$("#feed-list");if(!list.length){root.innerHTML='<div class="empty">Здесь появятся найденные возможности.<br>Добавьте первое объявление, чтобы начать.</div>';return}root.innerHTML=list.map(x=>`<article class="opportunity ${x.ranking_label}"><div><div class="vehicle-title"><a href="${escapeHtml(x.offer_url)}" target="_blank" rel="noreferrer">${escapeHtml(x.vehicle_make)} ${escapeHtml(x.vehicle_model)}</a></div><div class="vehicle-meta">${x.vehicle_year||"Год не указан"} · ${escapeHtml(x.offer_title)}</div><div class="ranking-reason">${escapeHtml(x.ranking_reasons[0]||"Недостаточно данных для полного объяснения")}</div></div><div><div class="cell-label">Прогноз прибыли</div><div class="cell-value">${money(x.expected_profit,x.currency)}</div></div><div><div class="cell-label">${priorityLabel(x.ranking_label)}</div><div class="score ${x.latest_scores.opportunity==null?"empty":""}" title="${escapeHtml(x.ranking_reasons.join(" · "))}">${x.latest_scores.opportunity==null?"—":Math.round(x.latest_scores.opportunity)}</div></div><div><div class="cell-label">Статус</div><span class="status ${x.status}">${statusLabel(x.status)}</span></div><div class="actions">${actionsFor(x)}</div></article>`).join("")}
function actionsFor(x){let actions=`<button class="action" data-recalculate="${x.id}">Пересчитать</button>`;if(x.status==="new")actions+=`<button class="action" data-decision="evaluate" data-id="${x.id}">Оценивать</button><button class="action" data-decision="accept" data-id="${x.id}">Принять</button><button class="action" data-decision="reject" data-id="${x.id}">Отклонить</button>`;else if(x.status==="evaluating")actions+=`<button class="action" data-decision="accept" data-id="${x.id}">Принять</button><button class="action" data-decision="reject" data-id="${x.id}">Отклонить</button>`;else if(x.status==="rejected")actions+=`<button class="action" data-decision="reopen" data-id="${x.id}">Вернуть</button>`;else if(x.status==="accepted"&&!x.acquisition_id)actions+=`<button class="action" data-acquire="${x.id}">Начать покупку</button>`;return actions}
function escapeHtml(value){const div=document.createElement("div");div.textContent=value||"";return div.innerHTML}
function formatDate(value){return value?new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—"}
function renderAutomation(){const sources=$("#source-list");sources.innerHTML=state.sources.length?state.sources.map(x=>`<article class="source-card"><div><div class="source-name">${escapeHtml(x.name)}</div><div class="source-url">${escapeHtml(x.endpoint_url)}</div></div><div><div class="cell-label">Следующий запуск</div><div>${formatDate(x.next_run_at)}</div></div><div class="source-state ${x.enabled?"enabled":"disabled"}">${x.enabled?"Активен":"Остановлен"}</div><div class="actions"><button class="action" data-run-source="${x.id}">Запустить</button><button class="action" data-toggle-source="${x.id}" data-enabled="${x.enabled}">${x.enabled?"Пауза":"Включить"}</button></div></article>`).join(""):'<div class="empty">Добавьте JSON-источник, чтобы импорт запускался автоматически.</div>';const names=Object.fromEntries(state.sources.map(x=>[x.id,x.name]));$("#run-list").innerHTML=state.runs.length?state.runs.slice(0,20).map(x=>`<article class="run-card"><div><strong>${escapeHtml(names[x.source_id]||"Источник")}</strong><div class="vehicle-meta">${formatDate(x.started_at)} · ${escapeHtml(x.trigger)}</div></div><div class="run-status ${x.status}">${escapeHtml(x.status)}</div><div>${x.created} новых · ${x.updated} обновлено · ${x.unchanged} без изменений</div><div>${x.error_count} ошибок</div></article>`).join(""):""}
async function load(){if(loadInFlight)return loadInFlight;loadInFlight=(async()=>{try{[state.markets,state.marketplaces,state.opportunities,state.sources,state.runs]=await Promise.all([request("/markets"),request("/markets/marketplaces"),request("/opportunities/feed"),request("/automation/sources"),request("/automation/runs")]);$("#system-state").textContent="Обновлено сейчас";fillMarketplaces();render();renderAutomation()}catch(error){$("#system-state").textContent="Нет связи";toast(error.message)}finally{loadInFlight=null}})();return loadInFlight}
function fillMarketplaces(){const select=$("[name=marketplace_id]");select.innerHTML=state.marketplaces.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join("")}
$("[data-open=listing]").addEventListener("click",()=>{if(!state.marketplaces.length){toast("Сначала настройте рынки и площадку");return}$("#listing-dialog").showModal()});
$("[data-open=import]").addEventListener("click",()=>{if(!state.marketplaces.length){toast("Сначала настройте рынки и площадку");return}$("#import-dialog").showModal()});
$("[data-open=source]").addEventListener("click",()=>$("#source-dialog").showModal());
document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",()=>$("#listing-dialog").close()));
document.querySelectorAll("[data-close-import]").forEach(button=>button.addEventListener("click",()=>$("#import-dialog").close()));
document.querySelectorAll("[data-close-source]").forEach(button=>button.addEventListener("click",()=>$("#source-dialog").close()));
$("#setup-button").addEventListener("click",async()=>{const button=$("#setup-button");button.disabled=true;try{let pl=state.markets.find(x=>x.code==="PL")||await request("/markets",{method:"POST",body:JSON.stringify({code:"PL",name:"Poland",default_currency:"PLN"})});if(!state.markets.some(x=>x.code==="UA"))await request("/markets",{method:"POST",body:JSON.stringify({code:"UA",name:"Ukraine",default_currency:"UAH"})});if(!state.marketplaces.length)await request("/markets/marketplaces",{method:"POST",body:JSON.stringify({market_id:pl.id,name:"Otomoto",slug:"otomoto",base_url:"https://www.otomoto.pl"})});toast("Рабочее пространство готово");await load()}catch(error){toast(error.message)}finally{button.disabled=false}});
$("#listing-form").addEventListener("submit",async event=>{event.preventDefault();const f=new FormData(event.currentTarget);const marketplace=state.marketplaces.find(x=>x.id===f.get("marketplace_id"));const market=state.markets.find(x=>x.id===marketplace?.market_id);const price=Number(f.get("price"));try{const offer=await request("/offers",{method:"POST",body:JSON.stringify({marketplace_id:f.get("marketplace_id"),external_id:"manual-"+crypto.randomUUID(),url:f.get("url"),title:`${f.get("make")} ${f.get("model")}`,mileage_km:Number(f.get("mileage_km"))||null,vehicle:{make:f.get("make"),model:f.get("model"),year:Number(f.get("year"))||null},price,currency:f.get("currency"),raw_data:{source:"manual-ui"}})});await request("/opportunities",{method:"POST",body:JSON.stringify({offer_id:offer.id,target_market_id:market.id,expected_purchase_price:price,expected_sale_price:Number(f.get("sale_price"))||null,expected_costs:Number(f.get("costs"))||0,currency:f.get("currency")})});$("#listing-dialog").close();event.currentTarget.reset();toast("Возможность создана");await load()}catch(error){$("#form-error").textContent=error.message}});
$("#import-form").addEventListener("submit",async event=>{event.preventDefault();const file=$("#import-file").files[0];if(!file)return;const isCsv=file.name.toLowerCase().endsWith(".csv");try{const content=await file.text();let result;if(isCsv){const response=await fetch(API+"/imports/listings/csv",{method:"POST",headers:{"Content-Type":"text/csv"},body:content});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`Ошибка ${response.status}`)}result=await response.json()}else{const parsed=JSON.parse(content);const payload=Array.isArray(parsed)?{provider:"json-file",records:parsed}:parsed;result=await request("/imports/listings",{method:"POST",body:JSON.stringify(payload)})}$("#import-dialog").close();event.currentTarget.reset();toast(`Импорт завершён: ${result.created} новых · ${result.updated} обновлено · ${result.unchanged} без изменений · ${result.errors.length} ошибок`);await load()}catch(error){$("#import-error").textContent=error.message}});
$("#source-form").addEventListener("submit",async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{await request("/automation/sources",{method:"POST",body:JSON.stringify({name:f.get("name"),endpoint_url:f.get("endpoint_url"),interval_minutes:Number(f.get("interval_minutes")),enabled:f.get("enabled")==="on"})});$("#source-dialog").close();event.currentTarget.reset();toast("Источник добавлен");await load()}catch(error){$("#source-error").textContent=error.message}});
$("#source-list").addEventListener("click",async event=>{if(event.target.dataset.runSource){toast("Запуск источника…");const run=await request(`/automation/sources/${event.target.dataset.runSource}/run`,{method:"POST"}).catch(error=>{toast(error.message);return null});if(run){toast(run.status==="failed"?`Ошибка: ${run.error_message}`:"Импорт источника завершён");await load()}}if(event.target.dataset.toggleSource){const enabled=event.target.dataset.enabled!=="true";try{await request(`/automation/sources/${event.target.dataset.toggleSource}`,{method:"PATCH",body:JSON.stringify({enabled})});toast(enabled?"Источник включён":"Источник остановлен");await load()}catch(error){toast(error.message)}}});
$("#feed-list").addEventListener("click",async event=>{const decision=event.target.dataset.decision;if(decision){try{await request(`/opportunities/${event.target.dataset.id}/decisions`,{method:"POST",body:JSON.stringify({decision,reason:"Решение из интерфейса DealerMind",actor:"owner",data_snapshot:{source:"web-ui"}})});toast("Решение сохранено");await load()}catch(error){toast(error.message)}}if(event.target.dataset.recalculate){try{await request(`/opportunities/${event.target.dataset.recalculate}/recalculate`,{method:"POST"});toast("Рейтинг пересчитан");await load()}catch(error){toast(error.message)}}if(event.target.dataset.acquire){const item=state.opportunities.find(x=>x.id===event.target.dataset.acquire);try{await request(`/opportunities/${item.id}/acquisition`,{method:"POST",body:JSON.stringify({currency:item.currency,agreed_price:item.expected_purchase_price})});toast("Покупка начата");await load()}catch(error){toast(error.message)}}});
document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));button.classList.add("active");state.filter=button.dataset.filter;render()}));document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible")load()});window.addEventListener("focus",load);setInterval(()=>{if(document.visibilityState==="visible")load()},30000);load();
