const API="/api/v1";const $=s=>document.querySelector(s);const esc=v=>{const d=document.createElement("div");d.textContent=v??"";return d.innerHTML};let activeSlug="";let pollTimer=null;
async function req(path,options={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...options});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||`Ошибка ${r.status}`);return b}
function ranks(id,data){const entries=Object.entries(data||{}).sort((a,b)=>b[1]-a[1]).slice(0,8);$(id).innerHTML=entries.length?entries.map(([name,count])=>`<div class="fleet-rank"><span>${esc(name)}</span><strong>${count}</strong></div>`).join(""):'<p class="section-hint">Нет данных в последнем снимке.</p>'}
function render(snaps){const s=snaps[0];if(!s){$("#fleet-summary").innerHTML='<div class="fleet-empty">Снимков пока нет. Запустите первый сбор.</div>';$("#fleet-chart").innerHTML="";ranks("#fleet-years",{});ranks("#fleet-fuel",{});ranks("#fleet-regions",{});return}$("#fleet-summary").innerHTML=`<article><span>Регистраций в периоде</span><strong>${s.records_count}</strong><small>${s.period_from} — ${s.period_to}</small></article><article><span>Последний снимок</span><strong>${new Date(s.collected_at).toLocaleDateString("ru-RU")}</strong><small>${esc(s.make)} ${esc(s.model)}</small></article><article><span>Снимков в истории</span><strong>${snaps.length}</strong><small>append-only история</small></article>`;const max=Math.max(...snaps.map(x=>x.records_count),1);$("#fleet-chart").innerHTML=[...snaps].reverse().map(x=>`<div class="fleet-bar"><strong>${x.records_count}</strong><i style="height:${Math.max(3,x.records_count/max*130)}px"></i><small>${x.period_to.slice(5)}</small></div>`).join("");ranks("#fleet-years",s.by_year);ranks("#fleet-fuel",s.by_fuel);ranks("#fleet-regions",s.by_region)}
async function load(){activeSlug=$("#fleet-profile").value;if(!activeSlug)return;render(await req(`/fleet-intelligence/profiles/${encodeURIComponent(activeSlug)}/snapshots`))}
function showStatus(message,ready=false){$("#fleet-status").textContent=message;$("#fleet-status").classList.toggle("ready",ready)}
function stopPolling(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}$("#fleet-collect").disabled=false;$("#fleet-collect").textContent="Собрать за 30 дней"}
async function checkProgress(){if(!activeSlug)return;try{const state=await req(`/fleet-intelligence/profiles/${encodeURIComponent(activeSlug)}/collection-status`);if(state.state==="collecting"){showStatus(state.message,false);return}stopPolling();if(state.state==="completed"){showStatus(state.message,true);await load()}else if(state.state==="failed")showStatus(state.message,false)}catch(e){stopPolling();showStatus(e.message,false)}}
async function startCollection(){activeSlug=$("#fleet-profile").value;const button=$("#fleet-collect");button.disabled=true;button.textContent="Сбор запущен";try{const state=await req(`/fleet-intelligence/profiles/${encodeURIComponent(activeSlug)}/collect`,{method:"POST"});showStatus(state.message,false);if(state.state==="collecting"){checkProgress();pollTimer=setInterval(checkProgress,2500)}else stopPolling()}catch(e){stopPolling();showStatus(e.message,false)}}
async function init(){const status=await req("/fleet-intelligence/status");showStatus(status.message,status.configured);const profiles=await req("/fleet-intelligence/profiles");$("#fleet-profile").innerHTML=profiles.map(p=>`<option value="${esc(p.slug)}">${esc(p.make)} ${esc(p.model)} ${esc(p.generation)}</option>`).join("");const target=new URLSearchParams(location.search).get("profile");if(target&&profiles.some(p=>p.slug===target))$("#fleet-profile").value=target;await load();$("#fleet-profile").onchange=()=>{stopPolling();load()};$("#fleet-collect").onclick=startCollection}
init().catch(e=>showStatus(e.message,false));
