const API="/api/v1";
const $=selector=>document.querySelector(selector);
const escapeHtml=value=>{const div=document.createElement("div");div.textContent=value||"";return div.innerHTML};
const money=value=>value==null?"—":new Intl.NumberFormat("ru-RU",{style:"currency",currency:"PLN",maximumFractionDigits:0}).format(value);
const number=value=>new Intl.NumberFormat("ru-RU").format(value||0);
const date=value=>value?new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";
const sellerLabel=value=>({private:"Частные лица",dealer:"Дилеры",unknown:"Не определено"})[value]||value;
let filterOptions=null;
let marketSnapshots=[];

async function request(path){const response=await fetch(API+path,{cache:"no-store"});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||`Ошибка ${response.status}`)}return response.json()}
function option(value){return `<option value="${escapeHtml(value)}">${escapeHtml(value)}</option>`}
function replaceOptions(name,values,placeholder,selected=""){const select=$(`[name=${name}]`);select.innerHTML=`<option value="">${placeholder}</option>`+values.map(option).join("");if(values.includes(selected))select.value=selected}
function updateModelOptions(selected=""){const make=$('[name=make]').value;const model=$('[name=model]');const models=make?(filterOptions?.models_by_make?.[make]||[]):[];replaceOptions("model",models,make?"Все модели этой марки":"Сначала выберите марку",selected);model.disabled=!make}
function fillOptions(filters){if(filterOptions)return;filterOptions=filters;replaceOptions("make",filters.makes,"Все марки");replaceOptions("fuel_type",filters.fuel_types,"Любое");replaceOptions("gearbox",filters.gearboxes,"Любая");replaceOptions("region",filters.regions,"Вся Польша");updateModelOptions()}

function renderSummary(summary){$("#stat-listings").textContent=number(summary.listings);$("#stat-active").textContent=`${number(summary.active_listings)} активных`;$("#stat-median").textContent=money(summary.median_price);$("#stat-new").textContent=number(summary.new_7_days);$("#stat-new-30").textContent=`${number(summary.new_30_days)} за 30 дней`;$("#stat-reductions").textContent=number(summary.price_reductions);$("#stat-days").textContent=summary.median_days_observed==null?"Срок пока не определён":`Медиана ${summary.median_days_observed} дней`}
function renderDistribution(items){const root=$("#price-distribution");if(!items.length){root.innerHTML='<div class="market-empty">Для распределения пока недостаточно цен.</div>';return}const maximum=Math.max(...items.map(x=>x.count));root.innerHTML=items.map(x=>`<div class="bar-column" title="${money(x.price_from)} — ${money(x.price_to)}: ${x.count}"><strong>${x.count}</strong><span style="height:${Math.max(8,x.count/maximum*120)}px"></span><small>${number(x.price_from/1000)}k</small></div>`).join("")}
function renderSellers(items){$("#seller-stats").innerHTML=items.map(x=>`<div><span>${sellerLabel(x.seller_type)}</span><strong>${number(x.listings)}</strong><small>Медиана ${money(x.median_price)}</small></div>`).join("")}
function renderRegions(items){$("#region-stats").innerHTML=items.length?items.map(x=>`<article><span>${escapeHtml(x.region)}</span><strong>${number(x.listings)} объявлений</strong><small>Медиана ${money(x.median_price)}</small></article>`).join(""):'<div class="market-empty">Регионы в объявлениях пока не распознаны.</div>'}
function percentileClass(value){return value==null?"unknown":value<=25?"good":value>=75?"high":"middle"}
function renderPositions(items){$("#listing-positions").innerHTML=items.length?items.map(x=>`<article class="position-row"><div><a href="${escapeHtml(x.url)}" target="_blank" rel="noreferrer"><strong>${escapeHtml(x.vehicle)}</strong></a><span class="market-label">${x.year||"Год не указан"} · ${sellerLabel(x.seller_type||"unknown")} · ${escapeHtml(x.region||"Регион не определён")}</span></div><div><span class="market-label">Цена</span><strong>${money(x.price)}</strong></div><div><span class="market-label">Наблюдаем</span>${x.days_observed} дней</div><div><span class="market-label">Позиция цены</span><span class="percentile ${percentileClass(x.price_percentile)}">${x.price_percentile==null?"Недостаточно аналогов":`${x.price_percentile}-й процентиль`}</span><small>${x.comparison_size} сопоставимых</small></div></article>`).join(""):'<div class="market-empty">Объявления по выбранным фильтрам не найдены.</div>'}
function renderHistory(items){$("#price-history").innerHTML=items.length?items.map(x=>`<article class="price-change-row"><div><a href="${escapeHtml(x.url)}" target="_blank" rel="noreferrer"><strong>${escapeHtml(x.vehicle)}</strong></a><span class="market-label">${date(x.changed_at)}</span></div><div><span class="old-price">${money(x.previous_price)}</span> → <strong>${money(x.current_price)}</strong></div><div class="price-drop">${x.change_percent}%</div></article>`).join(""):'<div class="market-empty">Снижений цены в выбранном сегменте пока нет.</div>'}
function renderVariants(items){const root=$("#variant-stats");root.innerHTML=items.length?items.map(x=>`<article class="variant-row"><div><strong>${escapeHtml(x.variant)}</strong><small>Полнота характеристик ${x.specification_completeness}% · уверенность ${escapeHtml(x.confidence)}</small></div><div><span>Медиана</span><strong>${money(x.median_price)}</strong></div><div><span>Диапазон</span><strong>${money(x.price_low)} — ${money(x.price_high)}</strong></div><div><span>Относительно модели</span><strong class="variant-premium ${x.premium_percent>=0?"positive":"negative"}">${x.premium_percent>0?"+":""}${x.premium_percent}%</strong><small>${number(x.sample_size)} объявлений</small></div></article>`).join(""):'<div class="market-empty">Для выбранной модели пока нет распознанных цен.</div>'}
function renderVariantModelChooser(make){const models=filterOptions?.models_by_make?.[make]||[];const root=$("#variant-stats");root.innerHTML=models.length?`<div class="variant-model-chooser"><strong>Выберите модель ${escapeHtml(make)}</strong><small>Покажем отдельные двигатели, приводы и комплектации</small><div>${models.map(model=>`<button type="button" class="variant-model-button" data-variant-model="${escapeHtml(model)}">${escapeHtml(model)}</button>`).join("")}</div></div>`:'<div class="market-empty">Для этой марки пока нет моделей с рыночными наблюдениями.</div>'}
async function loadVariants(){const form=$("#market-filters");const make=form.elements.make.value;const model=form.elements.model.value;const root=$("#variant-stats");if(!make){root.innerHTML='<div class="market-empty">Выберите марку в фильтрах.</div>';return}if(!model){renderVariantModelChooser(make);return}root.innerHTML='<div class="market-empty">Сравниваем версии модели…</div>';try{renderVariants(await request(`/market-intelligence/poland/variants?make=${encodeURIComponent(make)}&model=${encodeURIComponent(model)}`))}catch(error){root.innerHTML=`<div class="market-empty">${escapeHtml(error.message)}</div>`}}
function signed(value,suffix=""){if(value===0)return `0${suffix}`;return `${value>0?"+":""}${number(value)}${suffix}`}
function renderSnapshotSeries(sourceId){const rawSeries=marketSnapshots.filter(x=>x.source_id===sourceId).sort((a,b)=>new Date(a.captured_at)-new Date(b.captured_at));const byDay=new Map();for(const item of rawSeries){const day=new Date(item.captured_at).toLocaleDateString("sv-SE",{timeZone:"Europe/Warsaw"});byDay.set(day,item)}const series=[...byDay.values()];const root=$("#snapshot-chart");if(!series.length){$("#snapshot-summary").innerHTML="";root.innerHTML='<div class="market-empty">Для этого поиска снимков пока нет.</div>';return}const latest=series.at(-1);const previous=series.at(-2);const volumeDelta=previous?latest.listing_count-previous.listing_count:0;const priceDelta=previous&&latest.median_price!=null&&previous.median_price!=null?Number(latest.median_price)-Number(previous.median_price):0;$("#snapshot-summary").innerHTML=`<article><span>Последняя выборка</span><strong>${number(latest.listing_count)}</strong><small>${previous?signed(volumeDelta):"Первый снимок"}</small></article><article><span>Медианная цена</span><strong>${money(latest.median_price)}</strong><small>${previous?signed(priceDelta," PLN"):"Первый снимок"}</small></article><article><span>Новых</span><strong>${number(latest.new_count)}</strong><small>в последнем запуске</small></article><article><span>Снижения цены</span><strong>${number(latest.price_reduction_count)}</strong><small>${date(latest.captured_at)}</small></article>`;const maxVolume=Math.max(...series.map(x=>x.listing_count),1);const prices=series.map(x=>Number(x.median_price)||0);const minPrice=Math.min(...prices);const maxPrice=Math.max(...prices);root.innerHTML=series.slice(-30).map(x=>{const volumeHeight=Math.max(8,x.listing_count/maxVolume*110);const priceValue=Number(x.median_price)||0;const priceHeight=maxPrice===minPrice?65:20+(priceValue-minPrice)/(maxPrice-minPrice)*90;return `<div class="snapshot-point" title="${date(x.captured_at)} · ${x.listing_count} объявлений · ${money(x.median_price)}"><div><span class="snapshot-price" style="height:${priceHeight}px"></span><span class="snapshot-volume" style="height:${volumeHeight}px"></span></div><small>${new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit"}).format(new Date(x.captured_at))}</small></div>`}).join("")}
function renderSnapshotSources(items){marketSnapshots=items;const sources=[...new Map(items.map(x=>[x.source_id,x.source_name])).entries()];const select=$("#snapshot-source");select.innerHTML='<option value="">Выберите поиск</option>'+sources.map(([id,name])=>`<option value="${id}">${escapeHtml(name)}</option>`).join("");if(sources.length){select.value=sources[0][0];renderSnapshotSeries(sources[0][0])}}

function renderValuations(items){$("#valuation-history").innerHTML=items.length?items.map(x=>`<article class="valuation-row"><div><strong>${escapeHtml(x.vehicle)}</strong><span class="market-label">${date(x.calculated_at)}</span></div><div><span class="market-label">Оценка рынка</span><strong>${money(x.market_estimate)}</strong></div><div><span class="market-label">Диапазон</span>${money(x.price_low)} — ${money(x.price_high)}</div><div>${x.sample_size} аналогов</div></article>`).join(""):'<div class="market-empty">Оценок пока нет.</div>'}
function renderCollections(items){$("#collection-history").innerHTML=items.length?items.map(x=>`<details class="collection-card" data-id="${x.id}"><summary class="collection-summary"><div><strong>${escapeHtml(x.vehicle)}</strong><span class="market-label">${date(x.started_at)}</span></div><div>${escapeHtml(x.status)}</div><div>${x.usable_count} из ${x.found_count}</div><div>Показать аналоги ▾</div></summary><div class="collection-listings"><div class="market-empty">Откройте сбор для загрузки списка.</div></div></details>`).join(""):'<div class="market-empty">Сборов пока нет.</div>'}

function queryString(){const values=new FormData($("#market-filters"));const params=new URLSearchParams();for(const [key,value] of values){if(String(value).trim())params.set(key,value)}return params.toString()}
async function loadAnalytics(){const root=$("#listing-positions");root.innerHTML='<div class="market-empty">Обновляем аналитику…</div>';try{const data=await request(`/market-intelligence/poland?${queryString()}`);fillOptions(data.filters);renderSummary(data.summary);renderDistribution(data.price_distribution);renderSellers(data.seller_stats);renderRegions(data.region_stats);renderPositions(data.listings);renderHistory(data.price_history)}catch(error){root.innerHTML=`<div class="market-empty">${escapeHtml(error.message)}</div>`}}
async function loadHistory(){try{const [valuations,collections]=await Promise.all([request("/market-intelligence/valuations"),request("/market-intelligence/collections")]);renderValuations(valuations);renderCollections(collections)}catch(error){$("#valuation-history").innerHTML=`<div class="market-empty">${escapeHtml(error.message)}</div>`}}
async function loadSnapshots(){try{renderSnapshotSources(await request("/market-intelligence/poland/snapshots"))}catch(error){$("#snapshot-chart").innerHTML=`<div class="market-empty">${escapeHtml(error.message)}</div>`}}

$("#market-filters").addEventListener("submit",event=>{event.preventDefault();loadAnalytics();loadVariants()});
$("[name=make]").addEventListener("change",()=>{updateModelOptions();loadAnalytics();loadVariants()});
$("[name=model]").addEventListener("change",()=>{loadAnalytics();loadVariants()});
$("#variant-stats").addEventListener("click",event=>{const model=event.target.dataset.variantModel;if(!model)return;const select=$("[name=model]");select.value=model;loadAnalytics();loadVariants()});
$("#market-filters").addEventListener("reset",()=>setTimeout(()=>{updateModelOptions();loadAnalytics();loadVariants()}));
$("#snapshot-source").addEventListener("change",event=>renderSnapshotSeries(event.target.value));
$("#collection-history").addEventListener("toggle",async event=>{const details=event.target;if(!(details instanceof HTMLDetailsElement)||!details.open||details.dataset.loaded)return;const root=details.querySelector(".collection-listings");try{const items=await request(`/market-intelligence/collections/${details.dataset.id}/listings`);root.innerHTML=items.length?items.map(x=>`<article class="comparable-row"><div><a href="${escapeHtml(x.url)}" target="_blank" rel="noreferrer">${escapeHtml(x.title)}</a></div><div>${x.year||"—"}</div><div>${x.mileage_km==null?"—":number(x.mileage_km)+" км"}</div><div><strong>${money(x.price)}</strong></div></article>`).join(""):'<div class="market-empty">Подходящих объявлений не сохранено.</div>';details.dataset.loaded="true"}catch(error){root.innerHTML=`<div class="market-empty">${escapeHtml(error.message)}</div>`}},true);
loadAnalytics();loadSnapshots();loadHistory();
